foo: bar

# try a list of objects
stations:
  - name: Alster Radio
    uri: http://live96.106acht.de
  - name: Hamburg Zwei
    uri: http://stream.hamburg-zwei.de/hh2-live/mp3-192/hh2mediaplayer
  - name: Absolute Relax
    uri: http://absolut.hoerradar.de/absolutradio-relax-mp3
  - name: FFH Weihnachtsradio
    uri: http://mp3.ffh.de/fs_ffhchannels/hqxmas.mp3
